### ISSUE TITLE
Title links shouldn't go to GetIt for institutions that don't implement GetIt

### ISSUE THREAD

**Issue by barnabyalter** [NYULibraries/eshelf#99]
I saw a broken link report and noticed a number of errors in NewRelic that led me to the following discovery:

====

All the institutions except NYHS have access to e-Shelf through BobCat, but the following institutions do not implement GetIt: BHS, NYSID. (NYHS also doesn't implement GetIt but it doesn't implement e-Shelf either so it's not a problem for them.)

Instead they are driven to the Primo details page, but from the e-Shelf they are sent to GetIt because that is the default functionality for clicking title links in e-Shelf. This creates an inconsistent user experience and for some users actively shows them an error:

```
NoMethodError: undefined method `+' for nil:NilClass
…s/20160816195213/app/controllers/records_controller.rb:  135:in `getit'
               .org/jruby/RubyArray.java:1613:in `each'(undefined
             .org/jruby/RubyKernel.java:1242:in `catch'(undefined
       .org/jruby/RubyKernel.java:1930:in `public_send'(undefined
```

Instead of expecting a `getit_url` from the institution to always exist, we should check for it and if it's missing we should use the persistent linking into Primo instead. Something like this pseudo code:

```ruby
...
if current_primary_institution.getit_url.blank? && @record.external_system.primo?
  # But bury the persistent linker url in a config
  redirect_to "http://library.nyu.edu/persistent/lcn/#{@record.external_id}"
else
  redirect_to getit_url + @record.url
end
...
def getit_url
  # Default to the regular GetIt url without specifying inst
  # and bury that value in a config somewhere
  @getit_url ||= current_primary_institution.getit_url || getit_default_url
end
```

**Comment by barnabyalter** [comment]
@hab278 hey since you're working on eshelf could you throw this patch in there? Easy enough fix and get those errors off our back

**Comment by armmimic** [comment]
👍  on it

**Comment by hab278** [comment]
@barnabyalter 👍 On it!
